r"""
Build GIF animations for the loss-landscape simulations.

Each frame has:

    left:   3D loss landscape over a data-distribution heatmap floor
    right:  2D loss-landscape heatmap and 2D data-distribution heatmap

The script reads the .npz files generated by simulate_loss_landscape.py.
"""

from __future__ import annotations

import argparse
from io import BytesIO
from pathlib import Path
from typing import Dict, Iterable, List, Tuple

import matplotlib

matplotlib.use("Agg")

import matplotlib.pyplot as plt
import numpy as np
from matplotlib import cm, colors
from mpl_toolkits.mplot3d.art3d import Line3DCollection
from PIL import Image

from simulate_loss_landscape import DOMAIN_MAX, DOMAIN_MIN, bilinear_sample


EXPERIMENT_FILES = {
    "gradient_ascent": "gradient_ascent_simulation_data.npz",
    "no_movement_baseline": "no_movement_baseline_simulation_data.npz",
}


def load_experiments(out_dir: Path) -> Dict[str, Dict[str, np.ndarray]]:
    experiments = {}
    for name, filename in EXPERIMENT_FILES.items():
        path = out_dir / filename
        if not path.exists():
            raise FileNotFoundError(
                f"Missing {path}. Run simulate_loss_landscape.py before making GIFs."
            )
        data = np.load(path)
        experiments[name] = {key: data[key] for key in data.files if key != "config_json"}
    return experiments


def frame_schedule(n_rounds: int, n_steps: int, frames_per_round: int) -> List[Tuple[int, int]]:
    step_ids = np.linspace(0, n_steps, frames_per_round, dtype=int)
    step_ids = np.unique(step_ids)
    return [(round_id, int(step_id)) for round_id in range(n_rounds) for step_id in step_ids]


def add_3d_panel(
    ax,
    arrays: Dict[str, np.ndarray],
    round_id: int,
    step_id: int,
    experiment: str,
    z_min: float,
    z_max: float,
    density_norm: colors.Normalize,
    loss_norm: colors.Normalize,
    surface_stride: int,
    max_path_lines: int,
) -> None:
    u_axis = arrays["u_axis"]
    v_axis = arrays["v_axis"]
    density_grid = arrays["density_grid"]
    loss_grid = arrays["loss_grids"][round_id]
    trajectories = arrays["trajectories"][round_id]

    uu, vv = np.meshgrid(u_axis, v_axis, indexing="xy")
    sl = slice(None, None, surface_stride)
    uu_s = uu[sl, sl]
    vv_s = vv[sl, sl]
    loss_s = loss_grid[sl, sl]
    density_s = density_grid[sl, sl]

    floor_z = z_min
    density_facecolors = cm.viridis(density_norm(density_s))
    density_facecolors[..., 3] = 0.74

    ax.plot_surface(
        uu_s,
        vv_s,
        loss_s,
        cmap="cool",
        norm=loss_norm,
        linewidth=0,
        antialiased=True,
        alpha=0.76,
        rstride=1,
        cstride=1,
    )
    ax.plot_surface(
        uu_s,
        vv_s,
        np.full_like(uu_s, floor_z),
        facecolors=density_facecolors,
        linewidth=0,
        antialiased=False,
        shade=False,
    )

    start_pts = trajectories[0].astype(np.float64)
    current_pts = trajectories[step_id].astype(np.float64)
    current_loss = bilinear_sample(loss_grid, u_axis, v_axis, current_pts)

    segments = [
        [(float(u), float(v), floor_z), (float(u), float(v), float(z))]
        for (u, v), z in zip(current_pts, current_loss)
    ]
    ax.add_collection3d(
        Line3DCollection(
            segments,
            colors=[(0.62, 0.62, 0.62, 0.18)],
            linewidths=0.32,
            linestyles="dashed",
        )
    )

    if experiment == "gradient_ascent":
        ids = np.linspace(0, current_pts.shape[0] - 1, min(max_path_lines, current_pts.shape[0]), dtype=int)
        path_stride = max(1, step_id // 18) if step_id > 0 else 1
        for point_id in ids:
            path = trajectories[: step_id + 1 : path_stride, point_id].astype(np.float64)
            if len(path) < 2:
                continue
            path_z = bilinear_sample(loss_grid, u_axis, v_axis, path)
            ax.plot(
                path[:, 0],
                path[:, 1],
                path_z,
                color="#1B3F9A",
                linewidth=0.38,
                alpha=0.24,
            )

    ax.scatter(
        start_pts[:, 0],
        start_pts[:, 1],
        np.full(start_pts.shape[0], floor_z),
        s=7,
        c="#D45A72",
        alpha=0.28,
        depthshade=False,
    )
    ax.scatter(
        current_pts[:, 0],
        current_pts[:, 1],
        np.full(current_pts.shape[0], floor_z),
        s=8,
        c="#9E1F3D",
        alpha=0.72,
        depthshade=False,
    )
    ax.scatter(
        current_pts[:, 0],
        current_pts[:, 1],
        current_loss,
        s=9,
        c="#0A2A78",
        alpha=0.78,
        depthshade=False,
    )

    ax.set_xlim(DOMAIN_MIN, DOMAIN_MAX)
    ax.set_ylim(DOMAIN_MIN, DOMAIN_MAX)
    ax.set_zlim(z_min, z_max)
    ax.set_xlabel("X", labelpad=6)
    ax.set_ylabel("Y", labelpad=6)
    ax.set_zlabel("Z", labelpad=6)
    ax.view_init(elev=25, azim=-55)
    ax.grid(False)
    ax.set_box_aspect((1.0, 1.0, 0.72))


def add_heatmap_panel(
    ax,
    field: np.ndarray,
    points: np.ndarray,
    start_points: np.ndarray,
    title: str,
    cmap: str,
    norm: colors.Normalize,
    point_color: str,
) -> None:
    ax.imshow(
        field,
        origin="lower",
        extent=[DOMAIN_MIN, DOMAIN_MAX, DOMAIN_MIN, DOMAIN_MAX],
        cmap=cmap,
        norm=norm,
        interpolation="bicubic",
        aspect="equal",
    )
    ax.scatter(
        start_points[:, 0],
        start_points[:, 1],
        s=8,
        facecolors="none",
        edgecolors="0.45",
        linewidths=0.35,
        alpha=0.34,
    )
    ax.scatter(
        points[:, 0],
        points[:, 1],
        s=10,
        c=point_color,
        alpha=0.78,
        linewidths=0,
    )
    ax.set_title(title, fontsize=10, pad=5)
    ax.set_xlim(DOMAIN_MIN, DOMAIN_MAX)
    ax.set_ylim(DOMAIN_MIN, DOMAIN_MAX)
    ax.set_xlabel("X", fontsize=9)
    ax.set_ylabel("Y", fontsize=9)
    ax.tick_params(labelsize=8, length=2.5)


def render_frame(
    arrays: Dict[str, np.ndarray],
    experiment: str,
    round_id: int,
    step_id: int,
    z_min: float,
    z_max: float,
    density_norm: colors.Normalize,
    loss_norm: colors.Normalize,
    args: argparse.Namespace,
) -> Image.Image:
    fig = plt.figure(figsize=(12.6, 7.2), dpi=args.dpi)
    gs = fig.add_gridspec(
        2,
        2,
        width_ratios=[2.45, 1.0],
        height_ratios=[1.0, 1.0],
        left=0.03,
        right=0.985,
        bottom=0.06,
        top=0.90,
        wspace=0.12,
        hspace=0.30,
    )
    ax3d = fig.add_subplot(gs[:, 0], projection="3d")
    ax_loss = fig.add_subplot(gs[0, 1])
    ax_data = fig.add_subplot(gs[1, 1])

    add_3d_panel(
        ax3d,
        arrays,
        round_id,
        step_id,
        experiment,
        z_min,
        z_max,
        density_norm,
        loss_norm,
        args.surface_stride,
        args.max_path_lines,
    )

    trajectories = arrays["trajectories"][round_id]
    start_points = trajectories[0].astype(np.float64)
    current_points = trajectories[step_id].astype(np.float64)
    loss_grid = arrays["loss_grids"][round_id]
    density_grid = arrays["density_grid"]

    add_heatmap_panel(
        ax_loss,
        loss_grid,
        current_points,
        start_points,
        r"loss landscape $\mathcal{L}(x)$",
        "cool",
        loss_norm,
        "#0A2A78",
    )
    add_heatmap_panel(
        ax_data,
        density_grid,
        current_points,
        start_points,
        r"data distribution $P(x)$",
        "viridis",
        density_norm,
        "#9E1F3D",
    )

    pretty_name = "gradient ascent" if experiment == "gradient_ascent" else "no movement baseline"
    fig.suptitle(
        f"{pretty_name}: round {round_id + 1}/5, step {step_id}/100",
        fontsize=15,
        y=0.965,
    )

    buffer = BytesIO()
    fig.savefig(buffer, format="png", facecolor="white")
    plt.close(fig)
    buffer.seek(0)
    image = Image.open(buffer).convert("P", palette=Image.Palette.ADAPTIVE, colors=192)
    return image.copy()


def save_gif(frames: Iterable[Image.Image], out_path: Path, duration_ms: int) -> None:
    frames = list(frames)
    if not frames:
        raise ValueError("No frames were rendered.")
    frames[0].save(
        out_path,
        save_all=True,
        append_images=frames[1:],
        duration=duration_ms,
        loop=0,
        optimize=True,
    )


def make_experiment_gif(
    experiment: str,
    arrays: Dict[str, np.ndarray],
    out_path: Path,
    z_min: float,
    z_max: float,
    density_norm: colors.Normalize,
    loss_norm: colors.Normalize,
    args: argparse.Namespace,
) -> None:
    n_rounds = arrays["samples"].shape[0]
    n_steps = arrays["trajectories"].shape[1] - 1
    schedule = frame_schedule(n_rounds, n_steps, args.frames_per_round)
    frames = []
    for index, (round_id, step_id) in enumerate(schedule, start=1):
        print(f"{experiment}: frame {index}/{len(schedule)} round={round_id + 1} step={step_id}")
        frames.append(
            render_frame(
                arrays,
                experiment,
                round_id,
                step_id,
                z_min,
                z_max,
                density_norm,
                loss_norm,
                args,
            )
        )
    save_gif(frames, out_path, args.duration_ms)
    print(f"Saved {out_path}")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--out-dir",
        type=Path,
        default=Path("figures/loss_landscape/simulation_outputs"),
        help="Directory containing simulation .npz files.",
    )
    parser.add_argument("--frames-per-round", type=int, default=11)
    parser.add_argument("--duration-ms", type=int, default=180)
    parser.add_argument("--surface-stride", type=int, default=4)
    parser.add_argument("--max-path-lines", type=int, default=38)
    parser.add_argument("--dpi", type=int, default=120)
    parser.add_argument(
        "--experiments",
        nargs="+",
        choices=sorted(EXPERIMENT_FILES),
        default=["gradient_ascent", "no_movement_baseline"],
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    experiments = load_experiments(args.out_dir)

    z_min = min(float(arrays["loss_grids"].min()) for arrays in experiments.values()) - 0.75
    z_max = max(float(arrays["loss_grids"].max()) for arrays in experiments.values()) + 0.30
    density_grid = next(iter(experiments.values()))["density_grid"]
    density_norm = colors.Normalize(vmin=float(density_grid.min()), vmax=float(density_grid.max()))
    loss_norm = colors.Normalize(
        vmin=min(float(arrays["loss_grids"].min()) for arrays in experiments.values()),
        vmax=max(float(arrays["loss_grids"].max()) for arrays in experiments.values()),
    )

    for experiment in args.experiments:
        make_experiment_gif(
            experiment,
            experiments[experiment],
            args.out_dir / f"{experiment}_simulation.gif",
            z_min,
            z_max,
            density_norm,
            loss_norm,
            args,
        )


if __name__ == "__main__":
    main()
