#!/usr/bin/env python3
"""Build the completed Burgers + Darcy/CFlow result bundle.

This intentionally excludes the still-running NS2D experiment. It consumes the
tables generated by summarize_attack_objective_true_loss3.py and writes a clean
report directory with CSVs, PNG "board" figures, a Markdown report, and a small
upload manifest.
"""

from __future__ import annotations

import argparse
import json
import math
import shutil
from datetime import datetime, timezone
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


SYSTEMS = ("burgers1d", "darcy_cflow")
OBJECTIVE_ORDER = ["loss1", "loss2", "loss3"]


def fmt_float(value: float, digits: int = 4) -> str:
    if value is None or not np.isfinite(value):
        return "NA"
    return f"{value:.{digits}g}"


def fmt_mean_std(mean: float, std: float) -> str:
    return f"{fmt_float(mean, 4)} +/- {fmt_float(std, 3)}"


def ensure_dir(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)


def read_table(root: Path, name: str) -> pd.DataFrame:
    return pd.read_csv(root / "tables" / f"{name}.csv")


def filter_completed(df: pd.DataFrame) -> pd.DataFrame:
    return df[df["system"].isin(SYSTEMS)].copy()


def protocol_label(row: pd.Series) -> str:
    if row["system"] == "burgers1d":
        return f"Burgers eps={row['epsilon']}, alpha={row['alpha']}, N={int(row['n'])}"
    return f"Darcy K={int(row['epsilon'])}, alpha_flips={int(row['alpha'])}, N={int(row['n'])}"


def short_protocol(row: pd.Series) -> str:
    if row["system"] == "burgers1d":
        return f"eps={row['epsilon']}"
    return f"K={int(row['epsilon'])}"


def write_filtered_tables(analysis_root: Path, out_dir: Path) -> dict[str, Path]:
    tables_dir = out_dir / "tables"
    ensure_dir(tables_dir)
    written: dict[str, Path] = {}
    for name in [
        "all_samples",
        "objective_summary",
        "winner_summary",
        "paired_tests",
        "parameter_sweep_summary",
        "growth_rate_summary",
    ]:
        df = filter_completed(read_table(analysis_root, name))
        path = tables_dir / f"{name}_burgers_darcy.csv"
        df.to_csv(path, index=False)
        written[name] = path
    return written


def make_main_table(parameter: pd.DataFrame, objective: pd.DataFrame, winner: pd.DataFrame) -> pd.DataFrame:
    rows = []
    for _, p_row in parameter.iterrows():
        system = p_row["system"]
        protocol_id = p_row["protocol_id"]
        subset = objective[(objective["system"] == system) & (objective["protocol_id"] == protocol_id)]
        win = winner[(winner["system"] == system) & (winner["protocol_id"] == protocol_id)]
        values: dict[str, str] = {}
        ratios: dict[str, float] = {}
        for obj in OBJECTIVE_ORDER:
            rec = subset[subset["attack_objective"] == obj]
            if rec.empty:
                values[obj] = "missing"
                ratios[obj] = np.nan
                continue
            r = rec.iloc[0]
            values[obj] = fmt_mean_std(float(r["final_true_loss3_mean"]), float(r["final_true_loss3_std"]))
            ratios[obj] = float(r["ratio_mean"])
        win_row = win.iloc[0] if not win.empty else {}
        rows.append(
            {
                "system": system,
                "setting": short_protocol(p_row),
                "n": int(p_row["n"]),
                "steps": int(p_row["steps"]),
                "loss1 final true-loss3": values["loss1"],
                "loss2 final true-loss3": values["loss2"],
                "loss3 final true-loss3": values["loss3"],
                "loss3 ratio vs clean": fmt_float(ratios["loss3"], 4),
                "loss3 wins": int(win_row.get("loss3_wins", 0)) if len(win) else 0,
                "loss3 win rate": fmt_float(float(win_row.get("loss3_win_rate", np.nan)), 3) if len(win) else "NA",
                "best by mean": p_row["best_mean_objective"],
                "protocol_id": protocol_id,
            }
        )
    return pd.DataFrame(rows)


def draw_main_table(main: pd.DataFrame, out_path: Path) -> None:
    display = main[
        [
            "system",
            "setting",
            "n",
            "loss1 final true-loss3",
            "loss2 final true-loss3",
            "loss3 final true-loss3",
            "loss3 ratio vs clean",
            "loss3 win rate",
        ]
    ].copy()
    fig_h = 0.55 + 0.48 * (len(display) + 1)
    fig, ax = plt.subplots(figsize=(15, fig_h))
    ax.axis("off")
    table = ax.table(
        cellText=display.values,
        colLabels=display.columns,
        cellLoc="center",
        colLoc="center",
        loc="center",
    )
    table.auto_set_font_size(False)
    table.set_fontsize(8.5)
    table.scale(1.0, 1.35)
    for (row, col), cell in table.get_celld().items():
        cell.set_edgecolor("#d0d7de")
        if row == 0:
            cell.set_facecolor("#1f2937")
            cell.set_text_props(color="white", weight="bold")
        elif row % 2 == 0:
            cell.set_facecolor("#f6f8fa")
    fig.tight_layout()
    fig.savefig(out_path, dpi=220, bbox_inches="tight")
    plt.close(fig)


def draw_mean_bar(objective: pd.DataFrame, parameter: pd.DataFrame, out_path: Path) -> None:
    merged = objective.merge(
        parameter[["system", "protocol_id", "epsilon", "alpha", "n"]],
        on=["system", "protocol_id"],
        how="left",
    )
    merged["label"] = merged.apply(short_protocol, axis=1)
    systems = list(SYSTEMS)
    fig, axes = plt.subplots(1, 2, figsize=(14, 5), constrained_layout=True)
    colors = {"loss1": "#4c78a8", "loss2": "#f58518", "loss3": "#54a24b"}
    for ax, system in zip(axes, systems):
        df = merged[merged["system"] == system].copy()
        labels = list(dict.fromkeys(df["label"]))
        x = np.arange(len(labels))
        width = 0.24
        for i, obj in enumerate(OBJECTIVE_ORDER):
            rec = df[df["attack_objective"] == obj].set_index("label").reindex(labels)
            ax.bar(
                x + (i - 1) * width,
                rec["final_true_loss3_mean"],
                width,
                yerr=rec["final_true_loss3_se"],
                label=obj,
                color=colors[obj],
                capsize=3,
            )
        ax.set_title("Burgers 1D" if system == "burgers1d" else "Darcy/CFlow")
        ax.set_ylabel("final true loss3 mean")
        ax.set_xticks(x)
        ax.set_xticklabels(labels, rotation=25, ha="right")
        ax.grid(axis="y", alpha=0.25)
        ax.legend()
    fig.suptitle("Attack objective comparison: final true loss3")
    fig.savefig(out_path, dpi=220, bbox_inches="tight")
    plt.close(fig)


def draw_win_rate(parameter: pd.DataFrame, winner: pd.DataFrame, out_path: Path) -> None:
    merged = winner.merge(parameter[["system", "protocol_id", "epsilon", "alpha", "n"]], on=["system", "protocol_id"], how="left")
    merged["label"] = merged.apply(short_protocol, axis=1)
    fig, axes = plt.subplots(1, 2, figsize=(14, 4.8), constrained_layout=True)
    colors = {"loss1": "#4c78a8", "loss2": "#f58518", "loss3": "#54a24b"}
    for ax, system in zip(axes, SYSTEMS):
        df = merged[merged["system"] == system]
        labels = list(df["label"])
        x = np.arange(len(labels))
        width = 0.24
        for i, obj in enumerate(OBJECTIVE_ORDER):
            ax.bar(
                x + (i - 1) * width,
                df[f"{obj}_win_rate"],
                width,
                label=obj,
                color=colors[obj],
            )
        ax.set_title("Burgers 1D" if system == "burgers1d" else "Darcy/CFlow")
        ax.set_ylabel("per-sample win rate")
        ax.set_ylim(0, 1.05)
        ax.set_xticks(x)
        ax.set_xticklabels(labels, rotation=25, ha="right")
        ax.grid(axis="y", alpha=0.25)
        ax.legend()
    fig.suptitle("Which objective wins per sample?")
    fig.savefig(out_path, dpi=220, bbox_inches="tight")
    plt.close(fig)


def draw_loss3_ratio(parameter: pd.DataFrame, objective: pd.DataFrame, out_path: Path) -> None:
    loss3 = objective[objective["attack_objective"] == "loss3"].merge(
        parameter[["system", "protocol_id", "epsilon", "alpha", "n"]],
        on=["system", "protocol_id"],
        how="left",
    )
    loss3["label"] = loss3.apply(short_protocol, axis=1)
    fig, axes = plt.subplots(1, 2, figsize=(14, 4.8), constrained_layout=True)
    for ax, system in zip(axes, SYSTEMS):
        df = loss3[loss3["system"] == system]
        ax.plot(df["label"], df["ratio_mean"], marker="o", linewidth=2.5, color="#7f3c8d")
        for _, r in df.iterrows():
            ax.text(r["label"], r["ratio_mean"], fmt_float(float(r["ratio_mean"]), 3), ha="center", va="bottom", fontsize=8)
        ax.axhline(1.0, color="#6b7280", linestyle="--", linewidth=1)
        ax.set_title("Burgers 1D" if system == "burgers1d" else "Darcy/CFlow")
        ax.set_ylabel("loss3 objective final/clean true-loss3")
        ax.tick_params(axis="x", rotation=25)
        ax.grid(axis="y", alpha=0.25)
    fig.suptitle("Loss3 objective scales true loss3 across budgets")
    fig.savefig(out_path, dpi=220, bbox_inches="tight")
    plt.close(fig)


def copy_raw_subset(analysis_root: Path, out_dir: Path) -> Path:
    raw_dir = out_dir / "raw_subset"
    if raw_dir.exists():
        shutil.rmtree(raw_dir)
    ensure_dir(raw_dir)

    def ignore_smoke(_dir: str, names: list[str]) -> set[str]:
        return {name for name in names if "smoke" in name.lower()}

    shutil.copytree(analysis_root / "raw_runs" / "burgers", raw_dir / "burgers", ignore=ignore_smoke)
    shutil.copytree(analysis_root / "raw_runs" / "darcy", raw_dir / "darcy", ignore=ignore_smoke)
    logs_dir = raw_dir / "run_logs"
    ensure_dir(logs_dir)
    for log_path in sorted((analysis_root / "run_logs").glob("burgers*.log")) + sorted((analysis_root / "run_logs").glob("darcy*.log")):
        if "smoke" in log_path.name.lower():
            continue
        shutil.copy2(log_path, logs_dir / log_path.name)
    return raw_dir


def markdown_table(df: pd.DataFrame) -> str:
    if df.empty:
        return "_No rows._"
    rows = df.astype(str).replace({"nan": "NA", "NaN": "NA"})
    headers = [str(c) for c in rows.columns]

    def esc(value: str) -> str:
        return value.replace("|", "\\|")

    lines = [
        "| " + " | ".join(esc(h) for h in headers) + " |",
        "| " + " | ".join("---" for _ in headers) + " |",
    ]
    for _, rec in rows.iterrows():
        lines.append("| " + " | ".join(esc(str(rec[c])) for c in rows.columns) + " |")
    return "\n".join(lines)


def write_report(
    out_dir: Path,
    main: pd.DataFrame,
    objective: pd.DataFrame,
    winner: pd.DataFrame,
    paired: pd.DataFrame,
    figures: list[Path],
    archive_name: str,
) -> Path:
    report = out_dir / "burgers_darcy_cflow_summary.md"
    generated = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")

    key_cols = [
        "system",
        "setting",
        "n",
        "loss1 final true-loss3",
        "loss2 final true-loss3",
        "loss3 final true-loss3",
        "loss3 ratio vs clean",
        "loss3 wins",
        "loss3 win rate",
        "best by mean",
    ]
    paired_focus = paired[paired["comparison"].isin(["loss3_minus_loss1", "loss3_minus_loss2"])].copy()
    paired_focus = paired_focus[
        [
            "system",
            "protocol_id",
            "comparison",
            "n",
            "mean_diff",
            "cohen_dz",
            "paired_ttest_p_value",
            "wilcoxon_p_value",
            "bootstrap_ci95_low",
            "bootstrap_ci95_high",
        ]
    ]
    paired_focus["mean_diff"] = paired_focus["mean_diff"].map(lambda x: fmt_float(float(x), 5))
    paired_focus["cohen_dz"] = paired_focus["cohen_dz"].map(lambda x: fmt_float(float(x), 4))
    paired_focus["paired_ttest_p_value"] = paired_focus["paired_ttest_p_value"].map(lambda x: fmt_float(float(x), 4))
    paired_focus["wilcoxon_p_value"] = paired_focus["wilcoxon_p_value"].map(lambda x: fmt_float(float(x), 4))
    paired_focus["bootstrap_ci95_low"] = paired_focus["bootstrap_ci95_low"].map(lambda x: fmt_float(float(x), 5))
    paired_focus["bootstrap_ci95_high"] = paired_focus["bootstrap_ci95_high"].map(lambda x: fmt_float(float(x), 5))

    burgers = main[main["system"] == "burgers1d"]
    darcy = main[main["system"] == "darcy_cflow"]
    lines = [
        "# Burgers + Darcy/CFlow Attack Objective Summary",
        "",
        f"Generated: {generated}",
        "",
        "Scope: completed Burgers 1D and Darcy/CFlow runs only. The still-running NS2D experiment is intentionally excluded.",
        "",
        "## Executive conclusion",
        "",
        "- Across every completed Burgers setting, optimizing `loss3` gives the largest final true-loss3 mean and wins every paired sample.",
        "- Across every completed Darcy/CFlow setting, optimizing `loss3` also gives the largest final true-loss3 mean; its per-sample win rate rises from 70% at K=100 to 100% at K=875.",
        "- `loss1` and `loss2` are close to each other and often near the clean true-loss3 baseline, while `loss3` scales strongly with budget.",
        "",
        "## Completed configurations",
        "",
        "Burgers: fixed FNO1D model, nu=0.001, periodic 1D dataset, L2 PGD, 100 steps, 50 samples per setting.",
        "",
        markdown_table(burgers[key_cols]),
        "",
        "Darcy/CFlow: binary replacement attack, `steepest_replace`, 100 steps, alpha_flips=5, 20 samples per setting.",
        "",
        markdown_table(darcy[key_cols]),
        "",
        "## Figures",
        "",
    ]
    for fig in figures:
        lines.append(f"![{fig.stem}]({fig.relative_to(out_dir).as_posix()})")
        lines.append("")
    lines.extend(
        [
            "## Statistical comparison",
            "",
            "Positive `loss3_minus_loss*` means the `loss3` attack produced larger final true-loss3.",
            "",
            markdown_table(paired_focus),
            "",
            "## Files in this bundle",
            "",
            "- `tables/main_burgers_darcy_cflow.csv`: compact paper-facing result table.",
            "- `tables/*_burgers_darcy.csv`: filtered source tables for completed Burgers and Darcy/CFlow runs.",
            "- `figures/*.png`: high-resolution board/table figures suitable for pasting into a Mac whiteboard or slide deck.",
            "- `raw_subset/`: raw completed Burgers and Darcy/CFlow run outputs plus logs.",
            f"- `{archive_name}`: tar.gz archive of this bundle for R2 upload.",
            "",
            "## Notes",
            "",
            "- The phrase `DataFlow` in the request was treated as Darcy/CFlow, matching the completed result directories.",
            "- Raw NS2D outputs are not included here because that run is still active.",
        ]
    )
    report.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return report


def write_manifest(out_dir: Path, analysis_root: Path, archive_path: Path) -> None:
    files = []
    for path in sorted(out_dir.rglob("*")):
        if path.is_file():
            files.append({"path": str(path.relative_to(out_dir)), "bytes": path.stat().st_size})
    manifest = {
        "generated_at_utc": datetime.now(timezone.utc).isoformat(),
        "source_analysis_root": str(analysis_root),
        "scope": ["burgers1d", "darcy_cflow"],
        "archive": str(archive_path.name),
        "files": files,
    }
    (out_dir / "upload_manifest.json").write_text(json.dumps(manifest, indent=2), encoding="utf-8")


def build_bundle(analysis_root: Path, out_dir: Path) -> None:
    if out_dir.exists():
        shutil.rmtree(out_dir)
    ensure_dir(out_dir)
    ensure_dir(out_dir / "figures")

    written = write_filtered_tables(analysis_root, out_dir)
    objective = pd.read_csv(written["objective_summary"])
    winner = pd.read_csv(written["winner_summary"])
    paired = pd.read_csv(written["paired_tests"])
    parameter = pd.read_csv(written["parameter_sweep_summary"])

    main = make_main_table(parameter, objective, winner)
    main_path = out_dir / "tables" / "main_burgers_darcy_cflow.csv"
    main.to_csv(main_path, index=False)

    figures = [
        out_dir / "figures" / "mac_board_main_table.png",
        out_dir / "figures" / "mac_board_final_true_loss3_means.png",
        out_dir / "figures" / "mac_board_win_rates.png",
        out_dir / "figures" / "mac_board_loss3_ratio_curve.png",
    ]
    draw_main_table(main, figures[0])
    draw_mean_bar(objective, parameter, figures[1])
    draw_win_rate(parameter, winner, figures[2])
    draw_loss3_ratio(parameter, objective, figures[3])

    archive_name = f"{out_dir.name}.tar.gz"
    copy_raw_subset(analysis_root, out_dir)
    write_report(out_dir, main, objective, winner, paired, figures, archive_name)
    write_manifest(out_dir, analysis_root, Path(archive_name))
    archive_base = out_dir.parent / out_dir.name
    shutil.make_archive(str(archive_base), "gztar", root_dir=out_dir.parent, base_dir=out_dir.name)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--analysis-root", type=Path, default=Path("analysis_outputs/attack_objective_true_loss3_comparison_20260622"))
    parser.add_argument("--out-dir", type=Path, default=Path("analysis_outputs/attack_objective_true_loss3_comparison_20260622/burgers_darcy_cflow_summary"))
    args = parser.parse_args()
    build_bundle(args.analysis_root, args.out_dir)
    print(json.dumps({"out_dir": str(args.out_dir), "archive": str(args.out_dir) + ".tar.gz"}, indent=2))


if __name__ == "__main__":
    main()
